version: '3.8'

services:
  web:
    build: .
    command: gunicorn farasitedjango.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - farasite_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M

  nginx:
    image: nginx:1.21
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - farasite_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 300M

volumes:
  static_volume:

networks:
  farasite_network:
    driver: bridge 