# Generated by Django 4.1.13 on 2024-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Enemad',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
