# Generated by Django 5.0.4 on 2024-04-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains '},
        ),
    ]
