# Generated by Django 5.0.4 on 2024-04-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_managerspeople_position_alter_news_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerspeople',
            name='Position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='Grouping',
            field=models.CharField(max_length=255),
        ),
    ]
