# Generated by Django 4.1.13 on 2024-05-06 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_domain_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Title', models.TextField()),
                ('Description', models.TextField(blank=True, null=True)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.domain', to_field='domain')),
            ],
            options={
                'verbose_name': 'Comparison',
                'verbose_name_plural': 'Comparison',
            },
        ),
        migrations.CreateModel(
            name='ContentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Title', models.TextField()),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='static/images/')),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.domain', to_field='domain')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Content List',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='Sort',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qaofcontenttabs',
            name='TitleTab',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContentListChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Title', models.TextField()),
                ('Description', models.TextField(blank=True, null=True)),
                ('Icon', models.ImageField(upload_to='static/images/')),
                ('ContentTabs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.contentlist')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'List Child',
            },
        ),
        migrations.CreateModel(
            name='ContentComparisonBtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Title', models.TextField()),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='static/images/')),
                ('ContentTabs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.contentcomparison')),
            ],
            options={
                'verbose_name': 'sections',
                'verbose_name_plural': 'Comparison sections',
            },
        ),
    ]
