# Generated by Django 5.0.4 on 2024-04-21 10:12

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_news_grouping_alter_news_typeofcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField()),
                ('Domain', models.CharField(max_length=300)),
                ('Title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField()),
                ('Domain', models.CharField(max_length=300)),
                ('Subject', models.CharField(max_length=300)),
                ('Telephone', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='email',
            old_name='Domain',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='email',
            name='CreateAt',
        ),
        migrations.RemoveField(
            model_name='email',
            name='SenderEmail',
        ),
        migrations.RemoveField(
            model_name='news',
            name='TypeOfContent',
        ),
        migrations.AddField(
            model_name='branchsofcompany',
            name='Link',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='email',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='recipients',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.CharField(choices=[('info@isatispooya.com', 'info'), ('admin@isatispooya.com', 'admin'), ('fidip@isatispooya.com', 'fidip')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryvideo',
            name='ShortVideo',
            field=models.FileField(default=0, upload_to='static/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi']), website.models.validate_file_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='Email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Link',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='Grouping',
            field=models.CharField(choices=[('مقالات', 'مقالات')], default='مقالات', max_length=255),
        ),
    ]
