# Generated by Django 5.0.4 on 2024-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_managerspeople_position_alter_news_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerspeople',
            name='Position',
            field=models.CharField(choices=[], default='هیات مدیره', max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='Grouping',
            field=models.CharField(choices=[], default='مقالات', max_length=255),
        ),
    ]
