# Generated by Django 4.1.13 on 2024-05-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contentcomparison_contentlist_menu_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
