# Generated by Django 5.0.4 on 2024-04-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_subjectsubscription_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchsofcompany',
            old_name='Link',
            new_name='MapLink',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='Link',
            new_name='MapLink',
        ),
    ]
