# Generated by Django 5.0.4 on 2024-04-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_managerspeople_position_alter_news_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerspeople',
            name='Position',
            field=models.CharField(choices=[('هیات مدیره', 'هیات مدیره'), ('مدیرعامل', 'مدیرعامل')], default='هیات مدیره', max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='Grouping',
            field=models.CharField(choices=[('مقالات', 'مقالات'), ('اخبار سهام', 'اخبار سهام'), ('درباره بورس', 'درباره بورس')], default='مقالات', max_length=255),
        ),
    ]
