# Generated by Django 5.0.4 on 2024-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_link_branchsofcompany_maplink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Logo',
            new_name='Logo1',
        ),
        migrations.AddField(
            model_name='information',
            name='Logo2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
