# Generated by Django 5.0.4 on 2024-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_managerspeople_position_alter_news_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='TypeOfContent',
            field=models.CharField(choices=[('مقالات', 'مقالات'), ('اخبار', 'اخبار'), ('مقالات', 'مقالات'), ('مقالات', 'مقالات'), ('مقالات', 'مقالات'), ('اخبار', 'اخبار'), ('اخبار', 'اخبار'), ('اخبار', 'اخبار')], default='مقالات', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='Grouping',
            field=models.CharField(choices=[('مقالات', 'مقالات'), ('اخبار سهام', 'اخبار سهام'), ('درباره بورس', 'درباره بورس'), ('مقالات', 'مقالات'), ('مقالات', 'مقالات'), ('مقالات', 'مقالات'), ('اخبار', 'اخبار'), ('اخبار', 'اخبار'), ('اخبار', 'اخبار')], default='مقالات', max_length=255),
        ),
    ]
