# Generated by Django 5.0.4 on 2024-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_news_typeofcontent_alter_news_grouping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField()),
                ('Domain', models.CharField(max_length=255)),
                ('MegaMenu', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=500)),
                ('Link', models.CharField(max_length=255)),
                ('Icon', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='TypeOfContent',
        ),
        migrations.AlterField(
            model_name='managerspeople',
            name='Position',
            field=models.CharField(max_length=300),
        ),
    ]
