# Generated by Django 5.0.4 on 2024-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_galleryphoto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagersPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(max_length=300)),
                ('Title', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=300)),
                ('Telephone', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('Picture', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='PositionOfManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(max_length=300)),
                ('Title', models.CharField(max_length=300)),
                ('Senior', models.CharField(max_length=300)),
                ('Level', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['-CreateAt']},
        ),
    ]
