# Generated by Django 5.0.4 on 2024-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_managerspeople_positionofmanagers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerspeople',
            name='Position',
            field=models.CharField(choices=[], default='هیات مدیره', max_length=300),
        ),
    ]
