# Generated by Django 5.0.4 on 2024-04-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_menu_remove_news_typeofcontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introductionofcompanies',
            old_name='instagram',
            new_name='SubName',
        ),
        migrations.RemoveField(
            model_name='introductionofcompanies',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='introductionofcompanies',
            name='twitter',
        ),
        migrations.AddField(
            model_name='news',
            name='TypeOfContent',
            field=models.CharField(choices=[('مقالات', 'مقالات'), ('اخبار', 'اخبار'), ('مقالات', 'مقالات'), ('مقالات', 'مقالات'), ('مقالات', 'مقالات'), ('اخبار', 'اخبار'), ('اخبار', 'اخبار'), ('اخبار', 'اخبار')], default='مقالات', max_length=255),
        ),
        migrations.AlterField(
            model_name='managerspeople',
            name='Position',
            field=models.CharField(choices=[('هیات مدیره', 'هیات مدیره'), ('مدیرعامل', 'مدیرعامل')], default='هیات مدیره', max_length=300),
        ),
    ]
