# Generated by Django 5.0.4 on 2024-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_managerspeople_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionofmanagers',
            name='Senior',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
