# Generated by Django 5.0.4 on 2024-04-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_instagram_introductionofcompanies_subname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductionofcompanies',
            name='LongAboutUs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
