# Generated by Django 5.0.4 on 2024-04-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_positionofmanagers_senior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerspeople',
            name='Position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='Grouping',
            field=models.CharField(choices=[('مقالات', 'مقالات'), ('اخبار سهام', 'اخبار سهام'), ('درباره بورس', 'درباره بورس'), ('اخبار', 'اخبار'), ('مقالات', 'مقالات'), ('مقالات', 'مقالات'), ('اخبار', 'اخبار'), ('اخبار', 'اخبار'), ('مقالات', 'مقالات')], default='مقالات', max_length=255),
        ),
    ]
