# Generated by Django 5.0.4 on 2024-04-27 05:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_introductionofcompanies_longaboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductionofcompanies',
            name='Background',
            field=colorfield.fields.ColorField(default='#FF000000', image_field=None, max_length=25, samples=None),
        ),
    ]
