# Generated by Django 4.1.13 on 2024-06-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSuperMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='static/images/')),
                ('url', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('دکمه', 'Button'), ('لینک', 'link')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('vector', models.ImageField(upload_to='static/images/')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.domain', to_field='domain')),
                ('sub', models.ManyToManyField(to='menu.subsupermenu')),
            ],
        ),
    ]
